
FT_DPCM_PTR=$c000
	.export _danger_streets_music_data
        

;this file for FamiTone2 library generated by text2data tool
_danger_streets_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
; 00 : Main Menu
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word 307,256

.global FAMISTUDIO_DPCM_PTR

@instruments:
	.byte $30 ; 00 : Duty 0: Harsh
	.word @env5, @env18, @env10
	.byte $00
	.byte $30 ; 01 : Duty 0: Main (Release 1)
	.word @env36, @env18, @env10
	.byte $00
	.byte $30 ; 02 : Duty 0: Main (Release 2)
	.word @env36, @env18, @env10
	.byte $00
	.byte $30 ; 03 : Duty 0: Outro
	.word @env3, @env18, @env20
	.byte $00
	.byte $30 ; 04 : Duty 0: Outro Slide
	.word @env32, @env18, @env18
	.byte $00
	.byte $30 ; 05 : Duty 0: Reverb
	.word @env19, @env18, @env18
	.byte $00
	.byte $30 ; 06 : Duty 0: Sustain (Vol 1)
	.word @env26, @env18, @env10
	.byte $00
	.byte $30 ; 07 : Duty 0: Sustain (Vol 2)
	.word @env24, @env18, @env10
	.byte $00
	.byte $70 ; 08 : Duty 1: Harsh
	.word @env5, @env18, @env10
	.byte $00
	.byte $70 ; 09 : Duty 1: Main (Release 1)
	.word @env36, @env18, @env10
	.byte $00
	.byte $70 ; 0a : Duty 1: Main (Release 2)
	.word @env36, @env18, @env10
	.byte $00
	.byte $70 ; 0b : Duty 1: Reverb
	.word @env4, @env18, @env18
	.byte $00
	.byte $b0 ; 0c : Duty 2: Main
	.word @env37, @env18, @env10
	.byte $00
	.byte $b0 ; 0d : Duty 2: Reverb
	.word @env19, @env18, @env18
	.byte $00
	.byte $30 ; 0e : Noise: Break Snare
	.word @env31, @env6, @env18
	.byte $00
	.byte $30 ; 0f : Noise: Hat & Tom 1
	.word @env34, @env18, @env18
	.byte $00
	.byte $30 ; 10 : Noise: Hat & Tom 2
	.word @env42, @env18, @env18
	.byte $00
	.byte $30 ; 11 : Noise: Hat & Tom 3
	.word @env29, @env18, @env18
	.byte $00
	.byte $30 ; 12 : Noise: Hat & Tom 4
	.word @env43, @env18, @env18
	.byte $00
	.byte $30 ; 13 : Noise: Hat & Tom 5
	.word @env11, @env18, @env18
	.byte $00
	.byte $30 ; 14 : Noise: Hat & Tom 6
	.word @env38, @env18, @env18
	.byte $00
	.byte $30 ; 15 : Noise: Hat & Tom 7
	.word @env0, @env18, @env18
	.byte $00
	.byte $30 ; 16 : Noise: Hat & Tom 8
	.word @env40, @env18, @env18
	.byte $00
	.byte $30 ; 17 : Noise: Hat & Tom 9
	.word @env23, @env18, @env18
	.byte $00
	.byte $30 ; 18 : Noise: Hat & Tom 10
	.word @env28, @env18, @env18
	.byte $00
	.byte $30 ; 19 : Noise: Hat & Tom 11
	.word @env35, @env18, @env18
	.byte $00
	.byte $30 ; 1a : Noise: Hat & Tom 12
	.word @env2, @env18, @env18
	.byte $00
	.byte $30 ; 1b : Noise: Hat & Tom 13
	.word @env7, @env18, @env18
	.byte $00
	.byte $30 ; 1c : Noise: Hat & Tom 14
	.word @env14, @env18, @env18
	.byte $00
	.byte $30 ; 1d : Noise: Hat & Tom 15
	.word @env15, @env18, @env18
	.byte $00
	.byte $30 ; 1e : Noise: Hat & Tom 16
	.word @env17, @env18, @env18
	.byte $00
	.byte $30 ; 1f : Noise: Hat & Tom 17
	.word @env33, @env18, @env18
	.byte $00
	.byte $30 ; 20 : Noise: Hat & Tom 18
	.word @env16, @env18, @env18
	.byte $00
	.byte $30 ; 21 : Noise: Hat & Tom 19
	.word @env41, @env18, @env18
	.byte $00
	.byte $30 ; 22 : Noise: Snare 1
	.word @env8, @env18, @env18
	.byte $00
	.byte $30 ; 23 : Noise: Snare 2
	.word @env21, @env18, @env18
	.byte $00
	.byte $30 ; 24 : Noise: Snare 3
	.word @env25, @env18, @env18
	.byte $00
	.byte $30 ; 25 : Noise: Snare 4
	.word @env22, @env18, @env18
	.byte $00
	.byte $30 ; 26 : Noise: Snare 5
	.word @env30, @env18, @env18
	.byte $00
	.byte $30 ; 27 : Noise: Snare 6
	.word @env9, @env18, @env18
	.byte $00
	.byte $30 ; 28 : Noise: Snare 7
	.word @env39, @env18, @env18
	.byte $00
	.byte $30 ; 29 : Noise: Snare 8
	.word @env27, @env18, @env18
	.byte $00
	.byte $30 ; 2a : Triangle: Tom
	.word @env13, @env1, @env18
	.byte $00
	.byte $30 ; 2b : Triangle: Tom (Fill)
	.word @env13, @env12, @env18
	.byte $00
	.byte $30 ; 2c : Triangle: Tom (Plain)
	.word @env13, @env18, @env18
	.byte $00

@env0:
	.byte $cb,$cc,$c9,$c5,$c2,$00,$04
@env1:
	.byte $c0,$bf,$be,$bd,$bc,$bb,$ba,$b9,$b8,$00,$08
@env2:
	.byte $cb,$cc,$c9,$c6,$c3,$00,$04
@env3:
	.byte $c5,$c9,$c9,$c8,$00,$03
@env4:
	.byte $c3,$7f,$00,$00
@env5:
	.byte $ce,$cb,$ca,$c9,$00,$03
@env6:
	.byte $c0,$ba,$c0,$00,$02
@env7:
	.byte $cb,$cd,$ca,$c7,$c3,$00,$04
@env8:
	.byte $cd,$ce,$cc,$cb,$c9,$c7,$c6,$c4,$c3,$c1,$00,$09
@env9:
	.byte $cd,$ce,$cc,$ca,$c9,$c7,$c6,$c4,$c3,$c1,$00,$09
@env10:
	.byte $c0,$07,$c1,$c3,$c6,$c3,$c1,$bf,$bd,$ba,$bd,$bf,$00,$02
@env11:
	.byte $cd,$cb,$c8,$c5,$c2,$00,$04
@env12:
	.byte $c0,$bf,$c0,$c1,$00,$03
@env13:
	.byte $cf,$7f,$00,$00
@env14:
	.byte $cd,$cc,$c8,$c5,$c2,$00,$04
@env15:
	.byte $cc,$cd,$ca,$c6,$c3,$00,$04
@env16:
	.byte $cd,$cc,$c9,$c5,$c2,$00,$04
@env17:
	.byte $cd,$cc,$c9,$c6,$c3,$00,$04
@env18:
	.byte $c0,$7f,$00,$01
@env19:
	.byte $c4,$7f,$00,$00
@env20:
	.byte $c0,$27,$c1,$c3,$c6,$c3,$c1,$bf,$bd,$ba,$bd,$bf,$00,$02
@env21:
	.byte $cd,$ce,$cc,$ca,$c9,$c7,$c6,$c4,$c2,$c1,$00,$09
@env22:
	.byte $cd,$cd,$cc,$ca,$c9,$c7,$c5,$c4,$c2,$c1,$00,$09
@env23:
	.byte $cc,$cc,$ca,$c6,$c3,$00,$04
@env24:
	.byte $c2,$7f,$00,$00
@env25:
	.byte $ce,$ce,$cc,$cb,$c9,$c8,$c6,$c4,$c3,$c1,$00,$09
@env26:
	.byte $c1,$7f,$00,$00
@env27:
	.byte $cd,$cd,$cc,$cb,$c9,$c7,$c6,$c4,$c3,$c1,$00,$09
@env28:
	.byte $cd,$cd,$c9,$c6,$c3,$00,$04
@env29:
	.byte $cc,$cc,$c9,$c5,$c2,$00,$04
@env30:
	.byte $cd,$ce,$cc,$ca,$c9,$c8,$c6,$c4,$c3,$c1,$00,$09
@env31:
	.byte $cd,$ce,$cd,$cb,$ca,$c8,$c7,$c5,$c3,$c2,$c1,$00,$0a
@env32:
	.byte $c8,$7f,$00,$00
@env33:
	.byte $cc,$cb,$c9,$c6,$c3,$00,$04
@env34:
	.byte $cc,$cc,$c9,$c6,$c2,$00,$04
@env35:
	.byte $cc,$cc,$c9,$c6,$c3,$00,$04
@env36:
	.byte $c4,$c6,$c9,$c8,$0e,$c7,$0e,$c6,$0e,$c5,$0e,$c4,$0e,$c3,$00,$0d
@env37:
	.byte $c5,$c6,$c6,$ca,$cb,$cc,$cb,$ca,$c9,$c8,$c7,$00,$0a
@env38:
	.byte $cc,$cb,$c8,$c5,$c2,$00,$04
@env39:
	.byte $ce,$cd,$cc,$ca,$c9,$c7,$c5,$c4,$c2,$c1,$00,$09
@env40:
	.byte $cc,$cd,$ca,$c7,$c3,$00,$04
@env41:
	.byte $cb,$cc,$ca,$c7,$c3,$00,$04
@env42:
	.byte $cd,$cd,$ca,$c6,$c3,$00,$04
@env43:
	.byte $cc,$cc,$c8,$c5,$c2,$00,$04

@samples:
	.byte $30+.lobyte(FT_DPCM_PTR),$3e,$0c	;0 Sunsoft Bass: A# (Pitch:12)
	.byte $30+.lobyte(FT_DPCM_PTR),$3e,$0f	;1 Sunsoft Bass: A# (Pitch:15)
	.byte $20+.lobyte(FT_DPCM_PTR),$3f,$0d	;2 Sunsoft Bass: B (Pitch:13)
	.byte $20+.lobyte(FT_DPCM_PTR),$3f,$0e	;3 Sunsoft Bass: B (Pitch:14)
	.byte $00+.lobyte(FT_DPCM_PTR),$3f,$09	;4 Sunsoft Bass: C (Pitch:9)
	.byte $00+.lobyte(FT_DPCM_PTR),$3f,$0a	;5 Sunsoft Bass: C (Pitch:10)
	.byte $00+.lobyte(FT_DPCM_PTR),$3f,$0c	;6 Sunsoft Bass: C (Pitch:12)
	.byte $00+.lobyte(FT_DPCM_PTR),$3f,$0e	;7 Sunsoft Bass: C (Pitch:14)
	.byte $00+.lobyte(FT_DPCM_PTR),$3f,$0f	;8 Sunsoft Bass: C (Pitch:15)
	.byte $10+.lobyte(FT_DPCM_PTR),$3e,$08	;9 Sunsoft Bass: C# (Pitch:8)
	.byte $10+.lobyte(FT_DPCM_PTR),$3e,$0a	;10 Sunsoft Bass: C# (Pitch:10)
	.byte $10+.lobyte(FT_DPCM_PTR),$3e,$0d	;11 Sunsoft Bass: C# (Pitch:13)
	.byte $10+.lobyte(FT_DPCM_PTR),$3e,$0e	;12 Sunsoft Bass: C# (Pitch:14)
	.byte $40+.lobyte(FT_DPCM_PTR),$3f,$0a	;13 Sunsoft Bass: D (Pitch:10)
	.byte $40+.lobyte(FT_DPCM_PTR),$3f,$0e	;14 Sunsoft Bass: D (Pitch:14)

@song0ch0:
	.byte $fb, $01, $cf, $00, $a5, $96, $32, $91, $38, $91, $32, $91, $3c, $3f, $40, $9f, $3c, $91
@song0ch0loop:
@song0ref20:
	.byte $82, $28, $b9, $2c, $e1, $00, $a5, $96, $32, $91, $38, $91, $32, $91, $3c, $3f, $40, $9f, $3c, $91, $82, $40, $b9, $3c
	.byte $e1, $00, $a5, $96, $32, $91, $38, $91, $32, $91, $3c, $3f, $40, $9f, $3c, $91
	.byte $ff, $16
	.word @song0ref20
	.byte $a7, $84
@song0ref65:
	.byte $2e, $a5, $2c, $91, $2e, $a5, $2e, $91, $a7, $2c, $a5, $2c, $91, $2e, $b9, $a7
	.byte $ff, $10
	.word @song0ref65
	.byte $ff, $10
	.word @song0ref65
	.byte $2e, $a5, $2c, $91, $2e, $a5, $28, $91, $f9, $91, $98, $32, $91, $93, $32, $91, $38, $91, $32, $91, $3c, $91, $32, $a5
	.byte $40, $91
@song0ref113:
	.byte $93, $32, $91, $3c, $91, $32, $91, $38, $91, $32, $a5, $28, $91, $93, $28, $91, $2e, $91, $28, $91, $2e, $91, $34, $37
	.byte $38, $8b, $36, $91, $32, $91, $f9, $91, $32, $91, $93, $32, $91, $38, $91, $32, $91, $3c, $91, $32, $a5, $3c, $3f, $40
	.byte $8b
	.byte $ff, $12
	.word @song0ref113
	.byte $32, $91, $34, $37, $38, $8b, $36, $91, $2e, $91, $32, $91, $f9, $a5, $3d, $3f, $40, $d9, $3c, $91, $38, $91, $36, $91
	.byte $cf, $38, $9b, $3c, $9b, $3c, $3f, $40, $8b, $f9, $91, $94, $3c, $3f, $40, $8b, $93, $3c, $3f, $40, $8b, $44, $a5, $92
	.byte $46, $cd, $98, $3d, $3f, $40, $d9, $3c, $91, $38, $91, $36, $91, $cf, $38, $9b, $3c, $9b, $32, $91, $f9, $a5, $93, $90
	.byte $32, $91, $32, $91, $32, $91, $32, $cd, $84, $32, $cd, $32, $cd, $32, $b9, $32, $e1, $32, $cd, $32, $cd, $32, $b9, $32
	.byte $e1, $32, $cd, $32, $cd, $32, $b9, $32, $e1, $36, $cd, $36, $cd, $36, $b9, $36, $e1, $32, $a5, $32, $a5, $32, $9b, $32
	.byte $9b
@song0ref286:
	.byte $32, $91, $a7, $32, $a5, $32, $9b, $32, $9b, $32, $91, $a7, $32, $a5, $32, $9b, $32, $9b, $32, $91, $bb, $2e, $cd
	.byte $ff, $14
	.word @song0ref286
	.byte $a7, $32, $a5, $36, $9b, $40, $9b, $40, $91, $f9, $a5, $00, $a5, $8a
@song0ref326:
	.byte $32, $91, $36, $91, $38, $91, $3c, $91, $32, $91, $36, $91, $38, $91, $3c, $91
	.byte $ff, $10
	.word @song0ref326
	.byte $ff, $10
	.word @song0ref326
	.byte $ff, $10
	.word @song0ref326
	.byte $ff, $10
	.word @song0ref326
	.byte $36, $91, $38, $91, $3c, $91, $40, $b9, $46, $91, $4a, $a5, $4e, $91, $50, $91, $54, $91, $4a, $91, $4e, $91, $50, $91
	.byte $54, $a5, $58, $91, $5a, $91, $5e, $91, $54, $91, $58, $91, $5a, $91, $5e, $91, $62, $f5, $f7, $62, $a5, $a7, $96, $32
	.byte $91, $38, $91, $32, $91, $3c, $3f, $40, $9f, $3c, $91, $fd
	.word @song0ch0loop
@song0ch1:
	.byte $cf, $92, $32, $91, $38, $91, $32, $91, $3c, $3f, $40, $9f, $3c, $91, $38, $a5
@song0ch1loop:
@song0ref433:
	.byte $2e, $b9, $32, $e1, $32, $91, $38, $91, $32, $91, $3c, $3f, $40, $9f, $3c, $91, $38, $a5, $46, $b9, $44, $e1, $32, $91
	.byte $38, $91, $32, $91, $3c, $3f, $40, $9f, $3c, $91, $38, $a5
	.byte $ff, $16
	.word @song0ref433
	.byte $a7, $84
@song0ref474:
	.byte $38, $a5, $36, $91, $38, $a5, $38, $91, $a7, $36, $a5, $36, $91, $38, $b9, $a7
	.byte $ff, $10
	.word @song0ref474
	.byte $ff, $10
	.word @song0ref474
	.byte $38, $a5, $36, $91, $38, $a5, $36, $91, $f9, $a5, $8e, $36, $91, $9a, $32, $b9, $38, $91, $32, $91, $3c, $91, $32, $91
	.byte $93, $40, $a5, $32, $91, $3c, $91, $32, $91, $38, $91, $32, $91, $93, $28, $b9, $2e, $91, $28, $91, $2e, $91, $34, $37
	.byte $38, $8b, $36, $91, $32, $f9, $8f, $cf, $38, $91, $32, $91, $3c, $91, $32, $91, $93, $3c, $3f, $40, $9f, $32, $91, $3c
	.byte $91, $32, $91, $38, $91, $32, $91, $93, $28, $b9, $2e, $91, $32, $91, $34, $37, $38, $8b, $36, $91, $2e, $91, $32, $f9
	.byte $8f, $a7, $3d, $3f, $40, $d9, $3c, $91, $38, $91, $36, $e1, $38, $9b, $3c, $87, $93, $3c, $3f, $40, $ef, $84, $36, $91
	.byte $93, $36, $91, $3c, $a5, $40, $a5, $8c, $40, $a5, $a7, $9a, $3d, $3f, $40, $d9, $3c, $91, $38, $91, $36, $e1, $38, $9b
	.byte $3c, $87, $93, $32, $f9, $8f, $93, $80, $28, $91, $28, $91, $28, $91, $28, $cd, $94, $40, $cd, $3c, $cd, $38, $b9, $3c
	.byte $e1, $40, $cd, $3c, $cd, $38, $b9, $3c, $e1, $40, $cd, $3c, $cd, $38, $b9, $3c, $e1, $42, $cd, $40, $cd, $3c, $b9, $40
	.byte $e1, $40, $a5, $3c, $a5, $38, $9b, $3c, $9b
@song0ref697:
	.byte $40, $91, $a7, $3c, $a5, $38, $9b, $3c, $9b, $40, $91, $a7, $3c, $a5, $38, $9b, $3c, $9b, $38, $91, $bb, $36, $cd
	.byte $ff, $12
	.word @song0ref697
	.byte $40, $91, $a7, $3c, $a5, $40, $9b, $46, $9b, $4a, $91, $f9, $a5, $86
	.byte $ff, $10
	.word @song0ref326
	.byte $ff, $10
	.word @song0ref326
	.byte $ff, $10
	.word @song0ref326
	.byte $ff, $10
	.word @song0ref326
	.byte $ff, $10
	.word @song0ref326
	.byte $36, $91, $38, $91, $3c, $91, $40, $b9, $46, $91, $4a, $91, $93, $4e, $91, $50, $91, $54, $91, $4a, $91, $4e, $91, $50
	.byte $91, $54, $91, $93, $58, $91, $5a, $91, $5e, $91, $54, $91, $58, $91, $5a, $91, $5e, $91, $62, $f9, $a3, $cf, $88, $62
	.byte $cd, $92, $32, $91, $38, $91, $32, $91, $3c, $3f, $40, $9f, $3c, $91, $38, $a5, $fd
	.word @song0ch1loop
@song0ch2:
@song0ref819:
	.byte $d6, $4c, $83, $4c, $85, $4c, $83, $d4, $4c, $85, $00
@song0ref830:
	.byte $4c, $85, $00, $3c, $85, $00, $3c, $85, $00, $34
@song0ref840:
	.byte $8f
@song0ref841:
	.byte $00
@song0ref842:
	.byte $38, $83, $00, $8b, $38, $83, $00, $8b, $44, $8f, $00, $38, $83, $00, $8b, $38, $83, $00, $8b, $38, $83, $00, $8b, $44
	.byte $8f, $00, $38, $83, $00, $8b
@song0ch2loop:
	.byte $ff, $1e
	.word @song0ref842
	.byte $ff, $1e
	.word @song0ref842
@song0ref879:
	.byte $4c, $8f, $00, $4c, $8f, $00, $3c, $8f, $00, $34, $8f, $00, $4c, $85, $00, $4c, $85, $00, $89
	.byte $ff, $2a
	.word @song0ref830
	.byte $ff, $1e
	.word @song0ref842
	.byte $ff, $1e
	.word @song0ref842
@song0ref907:
	.byte $4c, $85, $00, $4c, $85, $00, $3c, $85, $00, $34, $85, $00, $4c, $85, $00, $3c, $85, $00, $3c, $85, $00, $34, $85, $00
	.byte $ff, $13
	.word @song0ref819
	.byte $85, $00, $34, $85
	.byte $ff, $1f
	.word @song0ref841
	.byte $ff, $1e
	.word @song0ref842
	.byte $ff, $1e
	.word @song0ref842
	.byte $ff, $13
	.word @song0ref879
	.byte $ff, $2a
	.word @song0ref830
	.byte $ff, $1e
	.word @song0ref842
	.byte $ff, $1e
	.word @song0ref842
	.byte $ff, $18
	.word @song0ref907
	.byte $ff, $13
	.word @song0ref819
	.byte $85, $00, $34, $85
	.byte $ff, $1f
	.word @song0ref841
	.byte $ff, $1e
	.word @song0ref842
	.byte $ff, $1e
	.word @song0ref842
	.byte $ff, $13
	.word @song0ref879
	.byte $ff, $2a
	.word @song0ref830
	.byte $ff, $1e
	.word @song0ref842
	.byte $ff, $1e
	.word @song0ref842
	.byte $ff, $18
	.word @song0ref907
	.byte $ff, $13
	.word @song0ref819
	.byte $85, $00, $34, $85
	.byte $ff, $1f
	.word @song0ref841
	.byte $ff, $1e
	.word @song0ref842
	.byte $ff, $1e
	.word @song0ref842
	.byte $ff, $13
	.word @song0ref879
	.byte $ff, $2a
	.word @song0ref830
	.byte $ff, $1e
	.word @song0ref842
	.byte $ff, $1e
	.word @song0ref842
	.byte $38, $83, $00, $8b, $44, $8f, $00, $44, $8f, $00, $44, $8f, $00, $44, $8f, $00, $95, $d8, $44, $83, $00, $9d, $d4
@song0ref1044:
	.byte $38, $83, $00, $c7, $38, $83, $00, $c7, $38, $83, $00, $b3, $38, $83, $00, $9f, $d8, $44, $83, $00, $8b, $d4, $38, $83
	.byte $00, $9f
	.byte $ff, $18
	.word @song0ref1044
	.byte $ff, $18
	.word @song0ref1044
	.byte $ff, $10
	.word @song0ref1044
	.byte $44, $8f, $00, $44, $8f, $00, $44
	.byte $ff, $20
	.word @song0ref840
	.byte $ff, $1e
	.word @song0ref842
	.byte $ff, $1e
	.word @song0ref842
	.byte $ff, $13
	.word @song0ref879
	.byte $ff, $2a
	.word @song0ref830
	.byte $ff, $1e
	.word @song0ref842
	.byte $ff, $1e
	.word @song0ref842
	.byte $ff, $18
	.word @song0ref907
	.byte $ff, $13
	.word @song0ref819
	.byte $85, $00, $34, $85
	.byte $ff, $1f
	.word @song0ref841
	.byte $ff, $1e
	.word @song0ref842
	.byte $ff, $1e
	.word @song0ref842
	.byte $ff, $13
	.word @song0ref879
	.byte $ff, $2a
	.word @song0ref830
	.byte $ff, $1e
	.word @song0ref842
	.byte $ff, $1e
	.word @song0ref842
	.byte $ff, $18
	.word @song0ref907
	.byte $ff, $13
	.word @song0ref819
	.byte $85, $00, $34, $85
	.byte $ff, $1f
	.word @song0ref841
	.byte $ff, $18
	.word @song0ref907
	.byte $ff, $13
	.word @song0ref819
	.byte $85, $00, $34, $85
	.byte $ff, $1f
	.word @song0ref841
	.byte $fd
	.word @song0ch2loop
@song0ch3:
	.byte $ac, $4c, $83, $bc, $4c, $85, $a4, $4c, $83, $9e, $4c
@song0ref1178:
	.byte $87, $4c, $87, $4c, $87, $4c, $87, $4c, $87, $00
@song0ref1188:
	.byte $87
@song0ref1189:
	.byte $58, $87, $00, $87
@song0ref1193:
	.byte $58, $87, $00, $87, $c4, $4c, $91, $9e, $58, $87, $00, $87, $58, $87, $00, $87, $58, $87, $00, $87, $c4, $4c, $91, $9e
	.byte $58, $87, $00, $87
@song0ch3loop:
	.byte $9e, $58, $87, $00, $87, $58, $87, $00, $87, $c4, $4c, $91, $a0, $58, $87, $00, $87, $a2, $58, $87, $00, $87
@song0ref1244:
	.byte $58, $87, $00, $87, $c6
@song0ref1249:
	.byte $4c, $91, $a2, $58, $87, $00, $87, $58, $87, $00, $87, $58, $87, $00, $87, $c6, $4c, $91, $a2, $58, $87, $00, $87, $58
	.byte $87, $00, $87, $58, $87, $00, $87, $c6, $4c, $91, $a2
@song0ref1284:
	.byte $58, $87, $00, $87, $4c, $87, $00, $87, $4c, $87, $00, $87, $b2, $4c, $87, $00, $87, $b8, $4c, $87, $00, $87, $a4, $4c
	.byte $87, $4c, $87, $00
	.byte $ff, $13
	.word @song0ref1178
@song0ref1315:
	.byte $c6, $4c, $91, $a4, $58, $87, $00
@song0ref1322:
	.byte $87
@song0ref1323:
	.byte $58, $87, $00, $87, $58, $87, $00, $87, $c6, $4c, $91, $a4, $58, $87, $00
@song0ref1338:
	.byte $87, $58, $87, $00, $87, $58, $87, $00, $87, $c8, $4c, $91, $a6
@song0ref1351:
	.byte $58, $87, $00, $87, $a8
@song0ref1356:
	.byte $58, $87, $00, $87, $58, $87, $00, $87, $ca, $4c, $91, $a8, $58, $87, $00
@song0ref1371:
	.byte $87, $58, $87, $00, $87, $58, $87, $00, $87, $ca, $4c, $91, $a8, $58, $87, $00, $87, $58, $87, $00, $87, $58, $87, $00
	.byte $87, $ca, $4c, $91, $a8, $58, $87, $00, $87, $4c, $87, $be, $4c, $87, $b2, $4c, $87, $4c, $87, $b4, $4c, $87, $4c, $87
	.byte $4c, $87, $4c, $87, $4c, $83, $a4, $4c, $85, $a2, $4c, $83, $b4, $4c, $87, $4c, $87, $4c, $87, $4c, $87, $4c, $87, $4c
@song0ref1443:
	.byte $87, $aa, $58, $87, $00, $87, $58, $87, $00, $87, $ca, $4c, $91, $aa, $58, $87, $00, $87, $58, $87, $00, $87, $58, $87
	.byte $00, $87, $ca, $4c, $91, $aa, $58, $87, $00, $87, $ac, $58, $87, $00, $87, $9e
	.byte $ff, $18
	.word @song0ref1193
	.byte $ff, $18
	.word @song0ref1189
	.byte $ae, $58, $87, $00, $87, $c0, $4c, $87, $00, $87, $a2
@song0ref1500:
	.byte $4c, $87, $00, $87, $4c, $87, $00, $87
@song0ref1508:
	.byte $4c, $87, $00, $87, $4c, $87, $4c, $87, $00, $87, $4c, $87, $4c, $87, $4c, $87, $4c, $87, $00, $87, $9e, $58, $87, $00
	.byte $87, $58, $87, $00, $87, $c6, $4c, $91, $9e, $58, $87, $00, $87, $58, $87, $00, $87, $58, $87, $00, $87, $cc, $4c, $91
	.byte $b0, $58, $87, $00, $87, $a4
	.byte $ff, $16
	.word @song0ref1323
	.byte $ff, $22
	.word @song0ref1315
	.byte $a8
@song0ref1569:
	.byte $4c
@song0ref1570:
	.byte $87, $4c, $87, $4c, $87, $4c, $87, $4c, $87, $4c, $87, $4c, $87, $4c, $87, $4c, $83, $a2, $4c, $85, $4c, $83, $a8, $4c
	.byte $87, $4c, $87, $4c, $87, $4c, $87, $4c, $87, $4c
	.byte $ff, $13
	.word @song0ref1371
	.byte $b2, $58, $87, $00, $87, $ca, $4c, $91, $b4, $58, $87, $00
	.byte $ff, $1d
	.word @song0ref1443
	.byte $b4, $58, $87, $00, $87, $58, $87, $00, $87, $ca, $4c, $91, $b4, $58, $87, $00, $87, $b6, $58, $87, $00, $87, $9e, $58
	.byte $87, $00, $87, $c4, $4c, $91, $9e, $58, $87, $00, $87, $4c, $87, $00, $87
	.byte $ff, $1c
	.word @song0ref1500
	.byte $58, $87, $00, $87, $58, $87, $00, $87, $c4, $4c, $91, $b2, $58, $87, $00, $87, $a0, $58, $87, $00, $87, $a2
	.byte $ff, $26
	.word @song0ref1244
	.byte $58, $87, $00, $87, $58, $87, $00, $87, $ce, $4c, $91
@song0ref1700:
	.byte $b0, $58, $87, $00, $87, $a4, $58, $87, $00, $87, $58, $87, $00, $87, $c6, $4c, $91, $a4, $58, $87, $00
	.byte $ff, $10
	.word @song0ref1570
	.byte $87, $4c, $83, $b2, $4c, $85, $b4, $4c, $83, $a4, $4c, $87, $4c, $87, $4c, $87, $4c, $87, $4c, $87, $4c
	.byte $ff, $39
	.word @song0ref1338
	.byte $58, $87, $00, $87, $b0, $58, $87, $00, $87, $d0, $4c, $91, $b4, $58, $87, $00, $87, $58, $87, $00, $87, $58, $87, $00
	.byte $87, $ca, $4c, $91, $b4, $58, $87, $00, $87, $4c, $87, $00, $87
	.byte $ff, $1c
	.word @song0ref1500
	.byte $58, $87, $00, $87, $ac
	.byte $ff, $18
	.word @song0ref1193
	.byte $ff, $1c
	.word @song0ref1189
	.byte $a0, $58, $87, $00, $87, $a2, $58, $87, $00, $87, $c4
	.byte $ff, $18
	.word @song0ref1249
	.byte $c6, $4c, $91, $4c, $91, $4c, $91, $4c, $91, $00, $91, $9c, $58, $91, $00, $91, $b8, $58, $87, $00, $c3, $a4, $58, $87
	.byte $00, $c3, $58, $87, $00, $af, $58, $87, $00, $9b, $c6, $4c, $91, $b2, $58, $87, $00, $9b, $a8
@song0ref1856:
	.byte $58, $87, $00, $c3, $58, $87, $00, $c3, $58, $87, $00, $af, $58, $87, $00, $9b, $d2, $4c, $91, $b2, $58, $87, $00, $9b
	.byte $b4
	.byte $ff, $10
	.word @song0ref1856
	.byte $c4, $4c, $91, $9e, $58, $87, $00, $9b
	.byte $ff, $10
	.word @song0ref1856
	.byte $c6, $4c, $91, $4c, $91, $4c, $91, $58, $91, $58, $91
	.byte $ff, $1e
	.word @song0ref1249
	.byte $ff, $11
	.word @song0ref1700
	.byte $ff, $17
	.word @song0ref1322
	.byte $c6, $4c, $91, $a4
	.byte $ff, $10
	.word @song0ref1284
	.byte $a8
	.byte $ff, $14
	.word @song0ref1508
	.byte $ff, $24
	.word @song0ref1356
	.byte $c4, $4c, $91, $b2, $58, $87, $00, $87, $b4, $58, $87, $00, $87, $58, $87, $00, $87, $ca, $4c, $91, $b4, $58, $87, $00
	.byte $ff, $1d
	.word @song0ref1443
	.byte $b4, $4c, $87, $c2, $4c, $87, $ac, $4c, $87, $9e, $4c, $87, $4c, $87, $4c, $87, $4c, $87, $4c
@song0ref1975:
	.byte $87, $4c, $83, $a8, $4c, $85, $a4, $4c, $83, $9e, $4c, $87, $4c, $87, $4c, $87, $4c, $87, $4c, $87, $4c
	.byte $ff, $1d
	.word @song0ref1188
	.byte $ba, $58, $87, $00, $87, $a2
	.byte $ff, $26
	.word @song0ref1244
	.byte $58, $87, $00, $87, $58, $87, $00, $87, $c6, $4c, $91, $b2, $58, $87, $00, $87, $b8, $4c, $87, $00, $87, $a4
	.byte $ff, $1c
	.word @song0ref1500
	.byte $ff, $16
	.word @song0ref1323
	.byte $ce, $4c, $91, $bc
	.byte $ff, $2e
	.word @song0ref1351
	.byte $58, $87, $00, $87, $58, $87, $00, $87, $c4, $4c, $91, $b2, $58, $87, $00, $87, $b4
	.byte $ff, $12
	.word @song0ref1569
	.byte $a4, $4c, $85, $9e, $4c, $83, $b4, $4c, $87, $4c, $87, $4c, $87, $4c, $87, $4c, $87, $4c, $87, $58, $87, $00, $87, $58
	.byte $87, $00, $87, $ca, $4c, $91, $b4, $58, $87, $00, $87, $58, $87, $00, $87, $b6, $58, $87, $00, $87, $c4, $4c, $91, $9e
	.byte $58, $87, $00
	.byte $ff, $10
	.word @song0ref1570
	.byte $ff, $12
	.word @song0ref1975
	.byte $87, $58, $87, $00, $87, $58, $87, $00, $87, $c4, $4c, $91, $9e, $58, $87, $00, $87, $b2, $58, $87, $00, $87, $a0, $58
	.byte $87, $00, $87, $c6, $4c, $91, $a2, $58, $87, $00, $87, $fd
	.word @song0ch3loop
@song0ch4:
	.byte $cf
@song0ref2159:
	.byte $0e, $91, $0e, $91, $0e, $91, $0e, $91, $0e, $91, $0e, $91, $0e, $91, $0e, $91
@song0ch4loop:
@song0ref2176:
	.byte $0c, $91, $0c, $91, $10, $91, $0a, $91, $0a, $91, $18, $91, $0a, $91, $18, $91
	.byte $ff, $10
	.word @song0ref2159
@song0ref2195:
	.byte $14, $91, $14, $91, $06, $91, $0a, $91, $0a, $91, $18, $91, $0a, $91, $18, $91
	.byte $ff, $10
	.word @song0ref2159
	.byte $ff, $10
	.word @song0ref2176
	.byte $ff, $10
	.word @song0ref2159
	.byte $ff, $10
	.word @song0ref2195
	.byte $ff, $10
	.word @song0ref2159
	.byte $ff, $10
	.word @song0ref2159
	.byte $ff, $10
	.word @song0ref2159
	.byte $ff, $10
	.word @song0ref2159
	.byte $ff, $10
	.word @song0ref2159
	.byte $ff, $10
	.word @song0ref2159
	.byte $0e, $91, $0e, $91, $0e, $91, $0e, $91, $0e, $91, $0e, $91, $0e, $91, $0c, $91, $0c, $91, $0c, $91, $0c, $91, $0c, $91
	.byte $0c, $91, $0c, $91, $0c, $91, $0c
@song0ref2272:
	.byte $91, $0e, $91, $0e, $91, $0e, $91, $12, $91, $0e, $91, $12, $91, $0e, $91, $0e, $91, $02, $91, $04, $91, $02, $91, $02
	.byte $91, $02, $91, $04, $91, $02, $91, $02, $91, $0c, $91, $0c, $91, $0c, $91, $10, $91, $02, $91, $04, $91, $02, $91, $02
	.byte $91, $0e, $91, $12, $91, $0e, $91, $0e, $91, $0e, $91, $12, $91, $0e, $91, $0e
	.byte $ff, $40
	.word @song0ref2272
@song0ref2339:
	.byte $91, $0a, $91, $0a, $91, $18, $91, $0a, $91, $0a, $91, $0a, $91, $18, $91, $0a, $91, $0c, $91, $0c, $91, $10, $91, $0c
	.byte $91, $0c, $91, $0c, $91, $10, $91, $0c, $91, $0e, $91, $0e, $91, $12, $91, $0e, $91, $12, $91, $0e, $91, $0e, $91, $12
@song0ref2387:
	.byte $91, $0e, $91, $0e, $91, $12, $91, $0e, $91, $0e, $91, $12, $91, $0e, $91, $12
	.byte $ff, $35
	.word @song0ref2339
	.byte $0e, $91, $0e, $91, $0e, $b5, $00, $95, $0e, $b5, $00, $95, $0e, $b5, $00, $95, $0e, $b5, $01, $0e, $a5, $0e, $91, $12
	.byte $91, $0e, $91, $02, $b5, $00, $95, $02, $b5, $00, $95, $02, $b5, $01, $02, $a5, $02, $91, $04, $91, $02, $91, $16, $c7
	.byte $00, $83, $16, $c7, $00, $83, $16, $b9, $16, $a5, $16, $91, $04, $91, $16, $91, $02, $b5, $00, $95, $02, $b5, $00, $95
	.byte $02, $b5, $01, $02, $a5, $04, $91, $02, $91, $04
	.byte $ff, $10
	.word @song0ref2387
@song0ref2491:
	.byte $91, $02, $91, $02, $91, $04, $91, $02, $91, $02, $91, $04, $91, $02, $91, $04, $91, $16, $91, $16, $91, $1a, $91, $16
	.byte $91, $16, $91, $1a, $91, $16, $91, $1a
	.byte $ff, $11
	.word @song0ref2491
	.byte $0e, $91, $0e, $91, $12, $91, $0e, $91, $0e, $91, $12, $91, $0e, $91, $12
	.byte $ff, $20
	.word @song0ref2491
	.byte $ff, $10
	.word @song0ref2387
@song0ref2547:
	.byte $91, $0e, $91, $0e, $91, $0e, $91, $12, $91, $0e, $91, $0e, $91, $04, $91, $12, $91, $02, $91, $02, $91, $02, $91, $04
	.byte $91, $02, $91, $02, $91, $1a, $91, $04, $91, $1c, $91, $1c, $91, $1c, $91, $1e, $91, $1c, $91, $1c, $91, $0c, $91, $1e
	.byte $91, $16, $91, $16, $91, $16, $91, $1a, $91, $16, $91, $16, $91, $08, $91, $1a
	.byte $ff, $40
	.word @song0ref2547
	.byte $ff, $11
	.word @song0ref2547
	.byte $0e, $91, $0e, $91, $12, $91, $0e, $91, $0e, $91, $12, $91, $0e, $91, $12, $91
	.byte $ff, $10
	.word @song0ref2159
	.byte $fd
	.word @song0ch4loop

